# Copyright © 2019-2020 Peter M. Stahl pemistahl@gmail.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expressed or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "grex"
version = "1.1.0"
authors = ["Peter M. Stahl <pemistahl@gmail.com>"]
description = """
grex generates regular expressions from user-provided test cases.
"""
homepage = "https://github.com/pemistahl/grex"
repository = "https://github.com/pemistahl/grex"
documentation = "https://docs.rs/grex"
license = "Apache-2.0"
readme = "README.md"
edition = "2018"
categories = ["command-line-utilities"]
keywords = ["pattern", "regex", "regexp"]

[dependencies]
colored = "1.9.2"
itertools = "0.8.2"
linked-list = "0.0.3"
ndarray = "0.13.0"
petgraph = {version = "0.5.0", default-features = false, features = ["stable_graph"]}
structopt = "0.3.8"
unic-char-range = "0.9.0"
unic-ucd-category = "0.9.0"
unicode-segmentation = "1.6.0"

[dev-dependencies]
assert_cmd = "0.12.0"
predicates = "1.0.2"
proptest = "0.9.5"
regex = "1.3.4"
rstest = "0.5.3"
tempfile = "3.1.0"

[badges]
travis-ci = {repository = "pemistahl/grex", branch = "master"}
codecov = {repository = "pemistahl/grex", branch = "master", service = "github"}
maintenance = {status = "actively-developed"}